### ISSUE TITLE
Add an option to include versions/tags in the report

### ISSUE THREAD

**Issue by sebastienvermeille** [devops-actions/load-used-actions#106]
Hi, 
I would like to propose working on a feature that would enrich the report with extra values.

**TLDR** I would like to know: How many projects use which actions, and which versions/sha of them are they using?

This opens a lot of possibility such as "the day a specific action's version/tag is highly critical, it is possible to trigger action to concerned repositories codeowners etc.

I will fork and open a PR for it, would you agree with a such improvement?

(I would like to work on that feature myself to contribute to this project as I really appreciate the concept if you agree)

**Comment by rajbos** [comment]
Sound like a good property to add and the information is already available where we detect the usage. 

So go ahead @sebastienvermeille!

**Comment by sebastienvermeille** [comment]
Hi @rajbos,
Thank you :) I opened the PR and could test it successfully on a private organization.
